version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: j1751502021
      MYSQL_DATABASE: noteAPIDatabase
      MYSQL_USER: notesAPI
      MYSQL_PASSWORD: j1751502021
